backend:
  name: github
  repo: v4ibhavsharma/litigra
  branch: main
  base_url: https://litigra-oauth.vaibhav-bb7.workers.dev
  site_domain: litigra.com
  auth_endpoint: /auth

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "blog"
    label: "Writing"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Vaibhav Sharma" }
      - { label: "Categories", name: "categories", widget: "list", default: ["Article"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
